# -*- coding: utf-8 -*-
# Generated by Django 1.11.17 on 2021-12-02 22:18
from __future__ import unicode_literals

from decimal import Decimal
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reservations', '0002_auto_20211202_1835'),
    ]

    operations = [
        migrations.AlterField(
            model_name='roomcategory',
            name='price',
            field=models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))]),
        ),
    ]
