# -*- coding: utf-8 -*-
# Generated by Django 1.11.17 on 2021-12-02 22:18
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reservations', '0003_auto_20211202_2218'),
    ]

    operations = [
        migrations.RenameField(
            model_name='roombooking',
            old_name='booking_id',
            new_name='booking',
        ),
        migrations.RenameField(
            model_name='roombooking',
            old_name='room_id',
            new_name='room',
        ),
    ]
