# -*- coding: utf-8 -*-
# Generated by Django 1.11.17 on 2021-12-05 23:45
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reservations', '0004_auto_20211202_2218'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='rooms',
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
    ]
