# -*- coding: utf-8 -*-
# Generated by Django 1.11.17 on 2021-12-06 12:11
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reservations', '0005_booking_rooms'),
    ]

    operations = [
        migrations.RenameField(
            model_name='booking',
            old_name='rooms',
            new_name='room_ids',
        ),
    ]
