# -*- coding: utf-8 -*-
# Generated by Django 1.11.17 on 2021-12-08 13:05
from __future__ import unicode_literals

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reservations', '0006_auto_20211206_1211'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booking',
            name='number_of_people',
            field=models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(1)]),
        ),
        migrations.AlterField(
            model_name='room',
            name='capacity',
            field=models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(0)]),
        ),
    ]
